export const Userdata = [
    {
        id:1,
        name:"Utsav",
        emial:"U@gmail.com",
        phone:1234
    },
    {
        id:2,
        name:"Mayur",
        emial:"M@gmail.com",
        phone:1234232323213
    },
    {
        id:3,
        name:"Milan",
        emial:"U@gmail.com",
        phone:123421321321
    }
]